### ISSUE TITLE
Can't exit Discord

### ISSUE THREAD

**Issue by Ads20000** [snapcrafters/discord#3]
When using Discord, I can't properly exit the application. File > Exit either does nothing or makes the window go 'black' (Discord's background colour, really) and then reloads Discord, with the 'black' screen still there in another window.

![screenshot from 2017-08-13 20-27-04](https://user-images.githubusercontent.com/3178485/29252810-f1916124-8065-11e7-8105-fb5b6d49b499.png)
_Image of the latter case_

Closing the app obviously (as expected) leaves Discord running in the background (though the indicator doesn't work). Using `kill` on the Discord PID (which I find with `top`) successfully kills the app, then I can reload it as normal from the Dash.

```
$ snap list
core          16-2.26.14          2462  canonical     -
discord       0.0.2               19    snapcrafters  -
$ snap version
snap    2.26.14
snapd   2.26.14
series  16
ubuntu  17.04
kernel  4.10.0-32-generic
```

**Comment by Ads20000** [comment]
Today when I tried to close Discord I had to run `kill 4142` then `kill 3687` twice to get it to close.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/discord/commit/ae04f74119151fb23aac1bea3fafaf8b50eff289.

**Comment by Ads20000** [comment]
Bug still exists with revision 23. More details [here](https://forum.snapcraft.io/t/auto-connections-for-discord/2392/7?u=ads20000).

**Comment by Cxpher** [comment]
Yep. Can confirm it does not exit unless the pid is killed. 

This should be fixed.

**Comment by popey** [comment]
It's not 100% consistent. Sometimes it re-opens, sometimes it doesn't. It's not been straightforward to debug.

**Comment by Cxpher** [comment]
Been consistent for me.

Not set to autostart. Installed from flathub.org.

If I right click the icon and exit, it does not. It just goes blank and reopens. Have to kill the pid.

**Comment by popey** [comment]
@Cxpher are you saying you have a build from flathub.org and it's broken, or you have a build from flathub and it works?

**Comment by popey** [comment]
It's also not confined to the Linux build. I just ran Discord on a Mac and it does exactly the same thing or relaunching and being near-impossible to kill - even with Force Quit.

**Comment by Ads20000** [comment]
Can you or @flexiondotorg get in touch with Discord about it? :)

**Comment by popey** [comment]
With the latest release of discord (revision 60) in stable channel, we believe this is now fixed.

**Comment by kevineaton** [comment]
Most recent version on 18.04, I hit the X, I choose exit, and nothing. I still hear all the voices in the chat. No way to exit unless I open terminal and kill the pid. This needs to be fixed ASAP.
